# Generated by Django 5.0.4 on 2024-04-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'enseignant", max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(help_text="Prénom de l'enseignant", max_length=255, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Salle de cours', max_length=255, verbose_name='Salle')),
                ('batiment', models.CharField(help_text='Bâtiment de cours', max_length=255, verbose_name='Bâtiment')),
                ('etage', models.CharField(help_text='Etage du bâtiment', max_length=255, verbose_name='Etage')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Libellé du matériel', max_length=255, verbose_name='Libelle')),
                ('budget', models.CharField(help_text='Budget utilisé', max_length=255, verbose_name='Budget')),
                ('acheteur', models.ForeignKey(help_text='Acheteur du matériel', on_delete=django.db.models.deletion.DO_NOTHING, related_name='acheteur', to='gestionMateriel.enseignant', verbose_name='Acheteur')),
                ('possesseur', models.ForeignKey(help_text='Possesseur du matériel', on_delete=django.db.models.deletion.DO_NOTHING, related_name='possesseur', to='gestionMateriel.enseignant', verbose_name='Possesseur')),
                ('responsable', models.ForeignKey(help_text='Responsable du matériel', on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable', to='gestionMateriel.enseignant', verbose_name='Responsable')),
                ('salle', models.ForeignKey(help_text='Position du matériel', on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMateriel.salle', verbose_name='Salle')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Libellé de l'accessoire", max_length=255, verbose_name='Libelle')),
                ('etat', models.CharField(help_text="Etat de l'accessoire", max_length=255, verbose_name='Etat')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMateriel.materiel', verbose_name="Matériel de l'accessoire")),
            ],
        ),
        migrations.CreateModel(
            name='Passation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePassation', models.DateField(help_text='Date de passation', verbose_name='Date de passation')),
                ('objectif', models.CharField(help_text='Objectif', max_length=255, verbose_name='Objectif')),
                ('donneur', models.ForeignKey(help_text='Enseignant donnant le matériel', on_delete=django.db.models.deletion.DO_NOTHING, related_name='donneur', to='gestionMateriel.enseignant', verbose_name='Donneur')),
                ('materiel', models.ForeignKey(help_text='Matériel échangé', on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMateriel.materiel', verbose_name='Matériel')),
                ('receveur', models.ForeignKey(help_text='Enseignant recevant le matériel', on_delete=django.db.models.deletion.DO_NOTHING, related_name='receveur', to='gestionMateriel.enseignant', verbose_name='Receveur')),
                ('lieu', models.ForeignKey(help_text="Salle d'échange du matériel", on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMateriel.salle', verbose_name='Salle')),
            ],
        ),
    ]
